void initializeMessageQueue();
void setupSignalHandlers();
void sendPID();
void cleanupAndExit();
void EndOfDayOrEarlyVoyage();
void handleBridgeQueue();
void checkAndBoardNextInQueue();
void performCruiseOperations();
void startCruisePreparation();
void performVoyage();
void performDisembarkation();
void waitForAllPassengersToDisembark();
void getReadyForNextCruise();
void sendStopSignal();
void handle_signal(int sig);